### ISSUE TITLE
Do we need still need two Dockerfiles?

### ISSUE THREAD

**Issue by joe94** [xmidt-org/talaria#115]
`Dockerfile` and `Dockerfile.local`  seem to be the exact same files.

I am guessing this was only needed in the glide days

**Comment by kcajmagic** [comment]
`Dockerfile.local` is used to bypass the vendoring(downloading dependencies) step. This will speed up the image creation for local testing, and gives you the ability to modify code in the vendor folder.

**Comment by joe94** [comment]
@kcajmagic mentioned that the difference should be that `go mod vendor` should be explicitly called in the main dockerfile while it should be omitted in `Dockerfile.local`

**Comment by joe94** [comment]
We no longer have a .local file
