### ISSUE TITLE
outbounder auth key should not be a list

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/talaria#124]
https://github.com/xmidt-org/talaria/blob/master/outbounder.go#L74
https://github.com/xmidt-org/talaria/blob/master/dispatcher.go#L63

the dispatcher only uses the first auth key from the list given by the outbounder.  We should make this more clear and just ask for one key, instead of providing the option for a slice of keys.

**Comment by joe94** [comment]
Change outbound.authKey into a single value as an immediate solution. Long term solutions include jwt or certs methods.
