### ISSUE TITLE
Custom Token Factory and AllClaims Interface

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/talaria#161]
The newer versions of bascule no longer have the `FullView()` function in the [`Attributes` interface](https://github.com/xmidt-org/bascule/blob/main/token.go#L39), talaria needs a custom implementation of `Attributes` that also implements a talaria specific interface:
```
type AllClaimer interface{
  GetAllClaims() map[string]interface{}
}
```
(Open to a different interface/function name, but you get the idea)

Then [this middleware](https://github.com/xmidt-org/talaria/blob/main/middleware.go#L18) can do a type assertion on the created token's `Attributes` to an `AllClaimer` in order to get the claims needed for the device metadata.

In order to get its own implementation into the token in the context, talaria should have its own token factory, similar to this one in bascule:
https://github.com/xmidt-org/bascule/blob/main/basculehttp/tokenFactory.go#L128
The token factory should create the talaria attribute implementation and put it in the token, instead of using `bascule.NewAttributes()`.

Another example of a custom token factory is here (wip):
https://github.com/xmidt-org/argus/blob/9f7c5a2e7fc2ed9c733783c8311f2330284ee14d/tokenFactory.go#L38

Tasks I know of:
- [ ] Create `AllClaimer` type interface.
- [ ] Create a struct that implements the bascule `Attributes` interface and `AllClaimer`.
- [ ] Create a new token factory that builds a bearer token using the new struct.
- [ ] Do a type assertion on the attributes from the token in the context in order to get all the claims and add them to the device metadata.

**Comment by johnabass** [comment]
This is a cleaner design, nicely done.  Using 'raw' somehow in the interface or method name might make things clear.  For example:

```
type RawAttributes interface {
    GetRawAttributes() map[string]interface{}
}
```

The main thing is to make it clear that this interface is obtaining the unprocessed (by `bascule`) attributes of something.
