### ISSUE TITLE
Talaria set content_type field to "json" for status events.

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/talaria#173]
Talaria sets the message field for "content_type" to "json", instead of "application/json" for online and offline status events.

https://github.com/xmidt-org/talaria/blob/3db2d63beee9e6ad84295fdfafd5c06e84392b44/deviceStatus.go#L55

https://github.com/xmidt-org/talaria/blob/3db2d63beee9e6ad84295fdfafd5c06e84392b44/deviceStatus.go#L95

**Comment by kristinaspring** [comment]
`wrp-go` has a constant for this that we can use here if we want:
https://github.com/xmidt-org/wrp-go/blob/33cbcf6c12ff75e4a5808566b27e2b4256c9a4b6/format.go#L26
