### ISSUE TITLE
Timeout is default 120 seconds for all incoming  Http requests.

### ISSUE THREAD

**Issue by Sachin4403** [xmidt-org/talaria#182]
Hi Team,

We had configured the [device.manager.requestTimeout](https://github.com/xmidt-org/talaria/blob/d86b9d63618dc32e81394781379964b3b8f0522e/talaria.yaml#L224) but talaria is using [default timeout](https://github.com/xmidt-org/talaria/blob/d86b9d63618dc32e81394781379964b3b8f0522e/primaryHandler.go#L64)   as it is expecting timeout filed from `inbound.timeout` which is not defined.

Here we had configured  the  [timeout handler](https://github.com/xmidt-org/talaria/blob/d86b9d63618dc32e81394781379964b3b8f0522e/primaryHandler.go#L245) which is taking the input from `inbound.timeout`

cc @joe94 @schmidtw

**Comment by joe94** [comment]
It looks like the location of that value changed in the config file while the path to parse it in code wasn't. 
I think a simple fix would be to update the path here https://github.com/xmidt-org/talaria/blob/d86b9d63618dc32e81394781379964b3b8f0522e/primaryHandler.go#L84 to be `device.manager.requestTimeout` instead.

**Comment by Sachin4403** [comment]
We can do it in both ways it is up to you how you want to solve this problem.

1. add a new property in talaria.yaml and talaria_spruce.yaml and deprecate the old key.
2. we need to update the keys in the code.

**Comment by Sachin4403** [comment]
Hi @joe94, it is fixed?
