### ISSUE TITLE
Unauthorised device connect /api/v2/device route

### ISSUE THREAD

**Issue by s-srakshe** [xmidt-org/talaria#332]
It seems Talaria allows connecting to it when no Authorization http header is passed in the request.

The following line of code registers a route that does not include any authorization middleware.
https://github.com/xmidt-org/talaria/blob/main/primaryHandler.go#L339

The authorization middleware comes into affect only if the Authorization http header is present in the request. The following line of code registers a route that it triggered when the header is present. As a result, any requests with invalid or expired JWT token are rejected.
https://github.com/xmidt-org/talaria/blob/main/primaryHandler.go#L331

As a result of https://github.com/xmidt-org/talaria/blob/main/primaryHandler.go#L339, any device can connect to Talaria by not including Authorization http header in it's request.
This can be used for DOS attacks. Is this intentional ? if so, Can it be made configurable ?

**Comment by denopink** [comment]
> Is this intentional ?

Yes it is intentional, we support fail open by default for connecting devices, meaning the device doesn't have to provide a token to connect.

> Can it be made configurable ?

Not atm, but you can create a separate issue requesting that feature (i.e. optional fail open) along with any additional info/context that'll help us understand your request and any concerns with the existing implementation (i.e. the default fail open). 🙂

**Comment by s-srakshe** [comment]
The concern is that unauthorised devices and unknown clients can connect and remain connected (re-connected) to Talaria and hence occupying the resources of Talaria. DDOS attack is further aggravated.

**Comment by denopink** [comment]
Sorry @s-srakshe , I just learned that openfail is in fact configurable. Give me a day (at most 2 days) to get you instructions on how to configure it

I'll also be closing #333

**Comment by denopink** [comment]
Hi @s-srakshe, this unfortunately got buried (I got pulled into other competing efforts) but @maurafortino is currently working on this now.

**Comment by s-srakshe** [comment]
Thanks for picking this up. Let me know whenever there is a progress.

**Comment by s-srakshe** [comment]
Thanks @maurafortino and @denopink for taking this up and getting it to closure.

**Comment by denopink** [comment]
no problem! there is a patch I need to put in before releasing. Should be ready by eod monday

**Comment by denopink** [comment]
the patch was released that monday, https://github.com/xmidt-org/talaria/releases/tag/v0.7.7

@maurafortino is currently validating the new (disable) open-fail feat

**Comment by maurafortino** [comment]
the disable open-fail feature has been tested and validated that it is working properly.
