### ISSUE TITLE
talaria.yaml uses incorrect inbound timeout key

### ISSUE THREAD

**Issue by iganev0886** [xmidt-org/talaria#358]
I believe that `requestTimeout` here https://github.com/Enterprise-RDK/talaria/blob/main/talaria.yaml#L326 should be actually `timeout` since the primary handler uses the path `inbound.timeout`: https://github.com/Enterprise-RDK/talaria/blob/main/primaryHandler.go#L91

I am new to this codebase and I might be wrong, but since we had issues with one of our devices taking longer than 120s  to process a specific request, we found that actually `timeout` is the correct value to set.

Kind regards, Ivo

**Comment by denopink** [comment]
yup, looks like this fell between the cracks. `talaria.yaml` serves as an example talaria config, we'll take a look and verify the rest is correct via https://github.com/xmidt-org/talaria/issues/359


Please sign the cla in your pr #357  and we can merge 🙂
