### ISSUE TITLE
make build with talaria

### ISSUE THREAD

**Issue by VicLin66** [xmidt-org/talaria#396]
Hi, I am following the READ.md to build talaria. But when I issued "make build" the messages showed "No rule to make target \`build\`". Is there other APP or package need to be installed?
I had followed Go instructions firstly, 
i.e.,
```
$ wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
$ tar xzf go1.11.linux-amd64.tar.gz
$ sudo mv go /usr/local
** Add Below Lines to the profile file (.bash_profile etc.)
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

Verify the version with below:
$ go version
go version go1.11 linux/amd64
```

**Comment by denopink** [comment]
@schmidtw may know more about our `make` process

**Comment by VicLin66** [comment]
I use "GO111MODULE=on go install github.com/xmidt-org/talaria@v0.9.2" to instead with "make buuld". Thanks.

**Comment by VicLin66** [comment]
close case.
