### ISSUE TITLE
service fails to start after upgrading to release 0.1.1-165

### ISSUE THREAD

**Issue by ganeshprasads** [xmidt-org/talaria#41]
Talaria service fails to start after upgrading from 0.1.1-153 to 0.1.1-165. Any dependency need to be changed?.

# tail -f /var/log/talaria/console.out 
`vendor/github.com/spf13/viper.(*Viper).Unmarshal(0x0, 0xaddba0, 0xc42000e900, 0xc420189790, 0x13)`
`        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:738 +0x2f`
`vendor/github.com/Comcast/webpa-common/service/servicecfg.NewEnvironment(0xd1ab40, 0xc4201ac500, 0xd1ae20, 0x0, 0x0, 0x0, 0xd1abc0, 0xc4201e0690)`
`        /root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/Comcast/webpa-common/service/servicecfg/environment.go:25 +0xd1`
`main.talaria(0xc42001e1e0, 0x1, 0x1, 0x0)`
`        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:120 +0xb1d
main.main.func1(0xc420076058)`
`        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:169 +0x49`
`main.main()`
`        /root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:172 +0x22`
# tail -f /var/run/talaria/talariaLog.log
`ts=2018-04-03T10:06:04.689560519Z caller=outbounder.go:233 level=info msg="Starting outbounder"`
`ts=2018-04-03T10:06:04.689575956Z level=info eventMap="unsupported value type"`
`ts=2018-04-03T10:06:04.689796743Z caller=webpa.go:483 level=info msg="starting server" name=talaria.health address=:8081`
`ts=2018-04-03T10:06:04.689812879Z caller=health.go:120 level=debug msg="Health Monitor Started"`
`ts=2018-04-03T10:06:04.69490963Z caller=webpa.go:506 level=info msg="starting server" name=talaria address=:8080`

**Comment by schmidtw** [comment]
@ganeshprasads is this still an issue?

**Comment by ganeshprasads** [comment]
@schmidtw Still facing the issue in 0.1.1-207
I was using the default yaml config and service terminates with below crash log:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x7b2535]
goroutine 1 [running]:
vendor/github.com/spf13/viper.(*Viper).AllKeys(0x0, 0x7, 0xc42017f868, 0x411f59)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1378 +0x45
vendor/github.com/spf13/viper.(*Viper).AllSettings(0x0, 0x4127a8)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:1458 +0x51
vendor/github.com/spf13/viper.(*Viper).Unmarshal(0x0, 0xb34140, 0xc42000e8b8, 0x0, 0x8)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/spf13/viper/viper.go:738 +0x2f
vendor/github.com/Comcast/webpa-common/service/servicecfg.NewEnvironment(0xd86660, 0xc42019e540, 0xd86960, 0x0, 0xc4200205a0, 0xd90480, 0xc4201b3680, 0x0)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/vendor/github.com/Comcast/webpa-common/service/servicecfg/environment.go:25 +0xd1
main.talaria(0xc42001e1b0, 0x1, 0x1, 0x0)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:96 +0x96e
main.main.func1(0xc42006e058)
	/root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:186 +0x49
main.main()
	/root/rpmbuild/BUILD/talaria-0.1.1/src/talaria/talaria.go:189 +0x22

talaria.yaml:
<b>---
    primary:
        address: ":8080"
    health:
        address: ":8888"
    pprof:
        address: ":9999"
    log:
        file      : "/var/run/talaria/talaria.log"
        level     : "DEBUG"
        maxSize   : 50
        maxBackup : 3<b>

**Comment by kristinaspring** [comment]
@ganeshprasads Is this still an issue?
