### ISSUE TITLE
User documentation request

### ISSUE THREAD

**Issue by WizzerWorks** [xmidt-org/talaria#44]
Is there any documentation on how to configure and stand up this WebPA Server component?

**Comment by schmidtw** [comment]
@njharter or @johnabass, now that https://github.com/Comcast/talaria/blob/master/etc/talaria/talaria.yaml is yaml, can you spend some time documenting the options more fully?

**Comment by kristinaspring** [comment]
Documentation for deployment:
https://xmidt.io/docs/operating/talaria/
documentation of configuration:
https://github.com/xmidt-org/talaria/blob/master/talaria.yaml
