### ISSUE TITLE
Docker Build error

### ISSUE THREAD

**Issue by ganeshprasads** [xmidt-org/talaria#96]
CentOS Linux release 7.6.1810 (Core)​
Docker version 18.09.7, build 2d0083d

Console Log:
$ git clone https://github.com/Comcast/talaria.git talaria_docker
$ cd talaria_docker/
$ docker build -t talaria:local .
Sending build context to Docker daemon  646.1kB
Step 1/18 : FROM golang:alpine as builder
 ---> 4e4b7a8b9495
Step 2/18 : MAINTAINER Jack Murdock <jack_murdock@comcast.com>
 ---> Using cache
 ---> fee8921fb0db
Step 3/18 : WORKDIR /go/src
 ---> Using cache
 ---> 0c1d12e154c2
Step 4/18 : RUN apk add --update --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ git curl
 ---> Using cache
 ---> 305cb5bf0af9
Step 5/18 : RUN curl https://glide.sh/get | sh
 ---> Using cache
 ---> adc58bddb7f7
Step 6/18 : COPY src/ /go/src/
 ---> Using cache
 ---> e9c19d1f61e7
Step 7/18 : RUN glide -q install --strip-vendor
 ---> Running in 51e9adbccd42

[ERROR] Failed to set version on github.com/jtacoma/uritemplates to 307ae868f90f4ee1b73ebe4596e0394237dacce8: Unexpected error while defensively cleaning up after possible derelict nested submodule directories: exit status 128
[ERROR] Failed to set references: Unexpected error while defensively cleaning up after possible derelict nested submodule directories: exit status 128 (Skip to cleanup)
The command '/bin/sh -c glide -q install --strip-vendor' returned a non-zero code: 1

**Comment by joe94** [comment]
Hey @ganeshprasads: we've made some changes since then. 

```
GO111MODULE=on go mod vendor
docker build -t talaria:local -f deploy/Dockerfile.local .
```
should now work. Please give it a try1!
