### ISSUE TITLE
Talaria service is not starting after upgrade 

### ISSUE THREAD

**Issue by anantcts** [xmidt-org/talaria#98]
Hi Team,

we have upgraded talaria from version:- 0.1.1-153.el6 to  0.1.1-244.el6. Earlier it was working fine and post-upgrade I am facing an issue with it. We have not made any change into the config file and we haven't patched our system post upgrade as well.

When I do service talaria start, the command executes successfully but when I do netstat -punta|grep 6000, it shows nothing. Also into the console.out file, I can see some error log printed.

**I have an observation as well which creates problem many of the times.** 
The default port of Talaria & Scytale is "6000" in 0.1.1-244.el6 which was not the case earlier. Can't we change it into the final build so that no conflict occurs post installation between these two applications & avoids manual input after every new installation or upgrade? 

![image](https://user-images.githubusercontent.com/52692223/61288712-5829e200-a7e5-11e9-89d3-1269fb767e5b.png)
![image](https://user-images.githubusercontent.com/52692223/61288733-6415a400-a7e5-11e9-84a1-d40d2b0ffb32.png)
[console.out.txt](https://github.com/xmidt-org/talaria/files/3396709/console.out.txt)

**Comment by kristinaspring** [comment]
Hello,

Are you still having issues?

**Comment by joe94** [comment]
Closing due to age.
